### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by stonedreamforest** [michaelkiros/FLIRTDB#1]
keep it up, cheers.

**Comment by Maktm** [comment]
Thanks! If you find it useful it'd be awesome if you could contribute back with your own signatures.

**Comment by Karaulov** [comment]
Possible to add old signatures visual studio 8 (v80,msvcr80.dll etc) ?

**Comment by Maktm** [comment]
Of course, if you want to contribute it, why not?! :)
