### ISSUE TITLE
my latest pull request accidentally committed binaries and put libcurl in the wrong directory

### ISSUE THREAD

**Issue by matthewperrin** [michaelkiros/FLIRTDB#13]
If you rewind it, I can make a new pull-request that fixes it or is it too late?

This will achieve this for you:

Confirm your local remote is called `origin`

`git remote`
`#should print 'origin'`

`git branch`
`#should print '* master'`

Once these two things are confirmed (they are the defaults) run:

`git checkout master`
`git reset --hard e2b12ab`
`git push -f`

After this I can submit a pull request for you to remedy the mistake I made!

@Maktm

**Comment by Maktm** [comment]
Ah, it's no problem. I should have been reviewing the pull request before merging. I've reset the current `HEAD` to what it was before your pull request. You can now send in a new pull request with all the correct changes and I'll merge it.

**Comment by matthewperrin** [comment]
I made the new pull request, I'll close this now.
