### ISSUE TITLE
IDA is not loading the signatures

### ISSUE THREAD

**Issue by poxyran** [michaelkiros/FLIRTDB#9]
Hi, I downloaded the files and decompress them in the sig folder. However, when hit SHIFT+F5 and then INS, none of the signatures is shown on the list. Using IDA7.

**Comment by vient** [comment]
Dunno if you still need the answer but you need to put them in `/sig/pc` (for x86/x64 FLIRTs) directory since signatures are defined for specific architectures.

**Comment by Maktm** [comment]
Closing issue. Please comment to have the issue reopened in the event that you are still experiencing the same issues. Thanks @vient
